version: '3.8'

services:
  db:
    image: nirajandangal/mariadb:latest
    container_name: mariadb_containers
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password123
      MYSQL_DATABASE: hello
      MYSQL_USER: test
      MYSQL_PASSWORD: test1223
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  app:
    image: nirajandangal/spring_boot_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_boot_app_containers
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/hello
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test1223
    ports:
      - "9192:9191"
    depends_on:
      - db

  nginx:
    image: nirajandangal/nginx:latest
    container_name: nginx_containers
    ports:
      - "8082:8081"
    volumes:
#      - ./nginx/spring.conf:/etc/nginx/conf.d/spring.conf
      - /home/jenkins/workspace/spring-automation/nginx/spring.conf:/etc/nginx/conf.d/spring.conf

    depends_on:
      - app

volumes:
  mariadb_data:
